version: '3.8'

services:
  db:
    image: postgres:15
    container_name: asseco-ds-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: filedb
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: asseco-ds
    container_name: asseco-ds-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/filedb
      R2DC_DATASOURCE_URL: r2dbc:postgresql://db:5432/filedb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
